import type { Group, Lesson } from './types'

export const groups: Group[] = [
  { id: 'UE-261', name: 'УЕ-261', course: 1 },
  { id: 'UI-261', name: 'УІ-261', course: 1 },
  { id: 'UK-261', name: 'УК-261', course: 1 },
  { id: 'UM-261', name: 'УМ-261', course: 1 },
  { id: 'UP-261', name: 'УП-261', course: 1 },
  { id: 'UP-262', name: 'УП-262', course: 1 },
]

const times = [
  ['08:00', '09:35'],
  ['09:50', '11:25'],
  ['11:40', '13:15'],
  ['13:30', '15:05'],
] as const

type RawLesson = [number, number, string, string?, string?, Lesson['weekType']?, string?, string?, Lesson['access']?]

const urls = {
  algo: 'https://us04web.zoom.us/j/2222763733?pwd=YUlLMVRvWUpnMVlCZG9IMjN1OHhxUT09',
  data: 'https://us05web.zoom.us/j/2495840685?pwd=xxuaxyolSnRb0Fol3xCLO6JD0MbDwz.1',
  mathPractice: 'https://us02web.zoom.us/j/82028486271?pwd=hdHNRafc8SMe79ffrwb7K37ANZbb39.1',
  mathLecture: 'https://us02web.zoom.us/j/86367529272?pwd=LoEZ5tEkyvTdO8cZc7QzDphTvzbdBz.1',
  ukPhysics: 'https://us05web.zoom.us/j/97397369995?pwd=Nmp6ZFIwTkdhdkZDVTVoSkM3VU4wdz09',
  ukAlgorithms: 'https://us04web.zoom.us/j/83365200611?pwd=Qmd4NHpabXpndHE0MjlFSHNEYmhNUT09',
  ukMath: 'https://us04web.zoom.us/j/71353589944?pwd=LvuvhQ6ZlNg3RuSb1wjuUVIijZR4Jn.1',
  ukModeling: 'https://meet.google.com/emn-bhaz-ooy',
  ueMath: 'https://us02web.zoom.us/j/82028486271?pwd=hdHNRafc8SMe79ffrwb7K37ANZbb39.1',
  ueIntegrity: 'https://us05web.zoom.us/j/82639580085?pwd=Zt6jfaXbqDTaIg8goQbudRlaBeGVBd.1',
  ueMeet: 'https://meet.google.com/ypn-idur-ebc',
  ueEconomics: 'https://meet.google.com/nir-rkqc-izb',
  umDiscrete: 'https://meet.google.com/hyp-njna-ujp',
  umMathLecture: 'https://meet.google.com/nwp-nvxj-sxi',
  umMathPractice: 'https://meet.google.com/nsg-drih-yet',
  umOs: 'https://us04web.zoom.us/j/7609594835?pwd=MGhuVllSVUo4bXFUeVVGTDI4QWRZUT09',
} as const

const access = {
  physics: { code: '327 340 5169', password: 'zFX2aJ' },
  programming: { code: '378 080 0730', password: '4T6Tq2' },
  algorithms: { code: '833 6520 0611', password: '12345' },
} as const

const schedules: Record<string, RawLesson[]> = {
  'UE-261': [
    [1, 1, 'Алгоритмізація та програмування', 'Лабораторна', 'Фонар Л.С.', 'all', '1–15', urls.algo],
    [1, 2, 'Алгоритмізація та програмування', 'Лекція', 'Фонар Л.С.', 'all', '1–15', urls.algo],
    [2, 2, 'Вища математика', 'Практика', 'Свинаренко А.А.', 'all', '1–15', urls.ueMath],
    [2, 3, 'Іноземна мова', 'Практика', 'Дьяченко Г.Ф.', 'all', '1–15', urls.ueMeet],
    [3, 1, 'Іноземна мова', 'Практика', 'Дьяченко Г.Ф.', 'all', '1–15'],
    [3, 2, 'Академічна доброчесність', 'Лекція', 'Лизогуб А.О.', 'odd', '1–15 нп', urls.ueIntegrity],
    [3, 2, 'Академічна доброчесність', 'Практика', 'Лизогуб А.О.', 'even', '2–14 пар', urls.ueIntegrity],
    [4, 1, 'Фізичне виховання'],
    [4, 2, 'Вища математика', 'Лекція', 'Хецеліус / Свинаренко А.А.', 'all', '1–15', urls.mathLecture],
    [5, 2, 'Основи економічної теорії', 'Лекція', 'Забарна Е.М.', 'all', '1–15', urls.ueEconomics],
    [5, 3, 'Основи економічної теорії', 'Практика', 'Забарна Е.М.', 'all', '1–15', urls.ueEconomics],
  ],
  'UI-261': [
    [1, 1, 'Алгоритмізація та програмування', 'Лабораторна', 'Фонар Л.С.', 'all', '1–15', urls.algo],
    [1, 2, 'Алгоритмізація та програмування', 'Лекція', 'Фонар Л.С.', 'all', '1–15', urls.algo],
    [1, 3, 'Структура та організація цифрових даних', 'Практика', 'Бондар О.А.', 'even', '2–14 пар', urls.data],
    [2, 2, 'Іноземна мова', 'Практика', 'Лебедєва О.В.', 'all', '1–15', urls.ueMeet],
    [2, 3, 'Вища математика', 'Практика', 'Свинаренко А.А.', 'all', '1–15', urls.mathPractice],
    [3, 2, 'Фізика', 'Лекція', 'Корнєва Н.М.', 'all', '1–15', undefined, access.physics],
    [3, 3, 'Фізика', 'Лабораторна', 'Корнєва Н.М.', 'odd', '1–15 нп', undefined, access.physics],
    [3, 3, 'Фізика', 'Практика', 'Корнєва Н.М.', 'even', '2–14 пар', undefined, access.physics],
    [4, 1, 'Фізичне виховання'],
    [4, 2, 'Вища математика', 'Лекція', 'Хецеліус / Свинаренко А.А.', 'all', '1–15', urls.mathLecture],
    [5, 2, 'Іноземна мова', 'Практика', 'Дьяченко Г.Ф.'],
    [5, 3, 'Структура та організація цифрових даних', 'Лекція', 'Бондар О.А.', 'odd', '1–15 нп', urls.data],
  ],
  'UK-261': [
    [1, 2, 'Фізика', 'Лекція', 'Ковальов Ю.В.', 'odd', '1–15 нп', urls.ukPhysics],
    [1, 2, 'Фізика', 'Практика', 'Ковальов Ю.В.', 'even', '2–14 пар', urls.ukPhysics],
    [1, 3, 'Алгоритми та методи обчислень', 'Лекція', 'Нестерюк О.Г.', 'all', '1–15', urls.ukAlgorithms, access.algorithms],
    [2, 2, 'Вища математика', 'Лекція', 'Буряк Д.В.', 'all', '1–15', urls.ukMath, { code: '713 5358 9944', password: '3hyK7H' }],
    [2, 3, 'Програмування', 'Лабораторна', 'Шендрик Є.В. / Головачова О.В.', 'odd', '3–15 нп', undefined, access.programming],
    [2, 3, 'Вища математика', 'Практика', 'Буряк Д.В.', 'even', '2–14 пар', urls.ukMath, { code: '713 5358 9944', password: '3hyK7H' }],
    [3, 1, 'Фізичне виховання'],
    [3, 2, '3-D моделювання', 'Лекція', 'Марущак Ю.В.', 'all', '1–15', urls.ukModeling],
    [3, 3, 'Іноземна мова', 'Практика', 'Дьяченко Г.Ф.'],
    [4, 2, '3-D моделювання', 'Лабораторна', 'Марущак Ю.В.', 'odd', '3–15 нп', urls.ukModeling],
    [4, 2, 'Алгоритми та методи обчислень', 'Лабораторна', 'Нестерюк О.Г.', 'even', '2–14 пар', urls.ukAlgorithms, access.algorithms],
    [5, 2, 'Програмування', 'Лекція', 'Головачова О.В.', 'all', '1–15', undefined, access.programming],
    [5, 3, 'Іноземна мова', 'Практика', 'Дьяченко Г.Ф.'],
  ],
  'UM-261': [
    [1, 2, 'Дискретні моделі та структури', 'Лекція', 'Пелих С.М.', 'all', '1–15', urls.umDiscrete],
    [1, 3, 'Програмування та теорія алгоритмів', 'Лекція', 'Сперанський В.О.', 'all', '1–15'],
    [2, 2, 'Вища математика', 'Лекція', 'Крапива Н.В.', 'all', '1–15', urls.umMathLecture],
    [2, 3, 'Вища математика', 'Практика', 'Крапива Н.В.', 'all', '1–15', urls.umMathPractice],
    [3, 2, 'Фізика', 'Лабораторна', '', 'odd', '1–15 нп'],
    [3, 2, 'Фізика', 'Практика', '', 'even', '2–14 пар'],
    [3, 3, 'Іноземна мова', 'Практика', 'Присяжнюк О.Я.'],
    [4, 1, 'Фізичне виховання'],
    [4, 2, 'Фізика', 'Лекція', 'Маслов О.В.'],
    [4, 3, 'Іноземна мова', 'Практика', 'Добровольська Ю.Л.'],
    [5, 2, 'Дискретні моделі та структури', 'Практика', 'Пелих С.М.', 'all', '1–15', urls.umDiscrete],
    [5, 3, 'Організація і архітектура ОС', 'Лекція', 'Максимов М.В.', 'odd', '3–15 нп', urls.umOs],
    [5, 3, 'Організація і архітектура ОС', 'Лабораторна', 'Максимов М.В.', 'even', '2–14 пар', urls.umOs],
  ],
  'UP-261': [
    [1, 2, 'Алгоритмізація та програмування', 'Лекція', 'Фонар Л.С.', 'all', '1–15', urls.algo],
    [1, 3, 'Структура та організація цифрових даних', 'Практика', 'Бондар О.А.', 'odd', '3–15 нп', urls.data],
    [2, 2, 'Фізика', 'Лабораторна', 'Корнєва Н.М.', 'odd', '1–15 нп', undefined, access.physics],
    [2, 2, 'Фізика', 'Практика', 'Корнєва Н.М.', 'even', '2–14 пар', undefined, access.physics],
    [2, 3, 'Вища математика', 'Практика', 'Свинаренко А.А.', 'all', '1–15', urls.mathPractice],
    [3, 2, 'Фізика', 'Лекція', 'Корнєва Н.М.', 'all', '1–15', undefined, access.physics],
    [3, 3, 'Іноземна мова', 'Практика', 'Андрейкова І.Б.'],
    [4, 1, 'Фізичне виховання'],
    [4, 2, 'Вища математика', 'Лекція', 'Хецеліус / Свинаренко А.А.', 'all', '1–15', urls.mathLecture],
    [4, 3, 'Іноземна мова', 'Практика', 'Цапенко Л.Ю.'],
    [5, 2, 'Алгоритмізація та програмування', 'Лабораторна', 'Фонар Л.С.', 'all', '1–15', urls.algo],
    [5, 3, 'Структура та організація цифрових даних', 'Лекція', 'Бондар О.А.', 'odd', '1–15 нп', urls.data],
  ],
  'UP-262': [
    [1, 2, 'Алгоритмізація та програмування', 'Лекція', 'Фонар Л.С.', 'all', '1–15', urls.algo],
    [1, 3, 'Структура та організація цифрових даних', 'Практика', 'Бондар О.А.', 'even', '2–14 пар', urls.data],
    [2, 2, 'Вища математика', 'Практика', 'Свинаренко А.А.', 'all', '1–15', urls.mathPractice],
    [2, 3, 'Фізика', 'Лабораторна', 'Корнєва Н.М.', 'odd', '1–15 нп', undefined, access.physics],
    [2, 3, 'Фізика', 'Практика', 'Корнєва Н.М.', 'even', '2–14 пар', undefined, access.physics],
    [3, 2, 'Фізика', 'Лекція', 'Корнєва Н.М.', 'all', '1–15', undefined, access.physics],
    [3, 3, 'Іноземна мова', 'Практика', 'Добровольська Ю.Л.'],
    [4, 1, 'Фізичне виховання'],
    [4, 2, 'Вища математика', 'Лекція', 'Хецеліус / Свинаренко А.А.', 'all', '1–15', urls.mathLecture],
    [4, 3, 'Алгоритмізація та програмування', 'Лабораторна', 'Фонар Л.С.', 'all', '1–15', urls.algo],
    [5, 2, 'Іноземна мова', 'Практика', 'Лебедєва О.В.'],
    [5, 3, 'Структура та організація цифрових даних', 'Лекція', 'Бондар О.А.', 'odd', '1–15 нп', urls.data],
  ],
}

export const getLessonsForGroup = (groupId: string): Lesson[] => (schedules[groupId] ?? []).map(([day, slot, subject, type = 'Заняття', teacher = '', weekType = 'all', period = '1–15', link, lessonAccess]) => ({
  id: `${groupId}-${day}-${slot}-${subject}-${period}`,
  subject,
  teacher,
  room: '',
  type: type.includes('Лек') ? 'lecture' : type.includes('Лаб') ? 'lab' : 'practice',
  period,
  link,
  access: lessonAccess,
  startTime: times[slot - 1][0],
  endTime: times[slot - 1][1],
  dayOfWeek: day,
  weekType,
}))
